defaults:
  - override hydra/job_logging: disabled
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

model: 1
note: "Weight: Inverse-Root"

data:
  weighting: inverse_root
  csv_path: data/generated/data.csv

training:
  batch_size: 64
  epochs: 10

optimizer:
  lr: 1e-3
  weight_decay: 1e-4