defaults:
  - override hydra/job_logging: disabled
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

model: 1
note: ""

data:
  weighting: inverse_root
  csv_path: data/generated/data.csv

training:
  batch_size: 64
  epochs: 50

optimizer:
  lr: 5e-4
  weight_decay: 1e-4