defaults:
  - override hydra/job_logging: disabled
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

model: 1
note: ""

training:
  batch_size: 64
  epochs: 10

optimizer:
  lr: 1e-3
  weight_decay: 1e-4